/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candf;

import org.testng.annotations.*;

public class AppTest {
    @Test public void appHasAGreeting() {
    }
}
