/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candf;

import com.candf.controller.RecommendationController;

import io.javalin.Javalin;

public class CzerniakowskieLakeApplication {

    public static void main(String[] args) {
        Configuration conf = new Configuration();
        RecommendationController controller = new RecommendationController(conf.getClothingRecommendation(),
                                                                           conf.getWeatherClient());
        Javalin application = conf.getApplication().start(8800);

        application.get("recommendation/{location}", controller::getClothingRecommendation);
    }
}
