/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candf;

import com.candf.controller.RecommendationController;

import io.javalin.Javalin;

public class CzerniakowskieLakeApplication {

    public static void main(String[] args) {
        Configuration conf = new Configuration();
        RecommendationController controller = new RecommendationController(conf.getClothingRecommendation(),
                                                                           conf.getWeatherClient());
        Javalin application = conf.getApplication().start(8800);
        printBaner();

        application.get("api/recommendation/{location}", ctx -> {
            var location = ctx.pathParam("location");
            var result = controller.getClothingRecommendation(location);
            if (!result.equals("")) {
                ctx.status(200).html(result);
            }
            else {
                ctx.status(400)
                   .html("<!DOCTYPE html><html><head><meta charset=\"utf-8\"></head><body><h1>"
                           + "Nie można było ustalić rekomendacji."
                           + "</h1></body></html>");
            }
        });
    }

    private static void printBaner() {
        System.out.println("""                  
                                
                   ___                 _      _                 _   _       _         _      \s
                  / __|______ _ _ _ _ (_)__ _| |_______ __ ____| |_(_)___  | |   __ _| |_____\s
                 | (__|_ / -_) '_| ' \\| / _` | / / _ \\ V  V (_-< / / / -_) | |__/ _` | / / -_)
                  \\___/__\\___|_| |_||_|_\\__,_|_\\_\\___/\\_/\\_//__/_\\_\\_\\___| |____\\__,_|_\\_\\___|
                                                                                             \s
                              
                """);
    }
}
