/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candf;

import org.testng.Assert;
import org.testng.annotations.*;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import static org.testng.Assert.*;

public class AppTest {

    @Test
    public void simpleApiTest() throws IOException, InterruptedException {
        HttpClient client = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_1_1)
                .connectTimeout(Duration.ofSeconds(30))
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build();

        HttpRequest req = HttpRequest.newBuilder()
                .GET()
                .uri(URI.create("http://localhost:8800/api/recommendation/warszawa"))
                .version(HttpClient.Version.HTTP_1_1)
                .build();

        var response = client.send(req, HttpResponse.BodyHandlers.ofString());

        Assert.assertEquals(response.statusCode(), 200);
        Assert.assertTrue(response.body().contains("Ubierz"));
        Assert.assertTrue(response.body().contains("Obecnie jest"));
    }
}
